In [55]:
import vk_api
import pandas as pd
import datetime
from tqdm import tqdm

In [62]:
vk_session = vk_api.VkApi(token='')

In [63]:
vk = vk_session.get_api()

In [64]:
# group_members список пользователей, состоящих в группе:
tools = vk_api.VkTools(vk_session)
group_members_id = tools.get_all('groups.getMembers', 1000, {'group_id': 108367462})
group_members_id = group_members_id['items']
print(len(group_members_id))

3531

In [68]:
# Друзья каждого пользовтеля, состоящего в группе:

all_dict_of_friends = []
for user_id in tqdm(group_members_id):
    
    try:
        dict_of_friends = vk.friends.get(user_id=user_id, order='hints', 
                             fields=['sex, bdate, city, country, education, universities, schools, relation'])
    except Exception:
        continue
    
    try:
        dict_of_friends = vk.friends.get(user_id=user_id, order='hints', 
                             fields=['sex, bdate, city, country, education, universities, schools, relation'])
    except Exception:
        continue

    if  (dict_of_friends['count'] > 25) & (dict_of_friends['count'] < 300):

        dict_of_friends['user_id'] = user_id
        all_dict_of_friends.append(dict_of_friends)
        list_for_df = []
        for k in all_dict_of_friends:
            for i in range(len(k['items'])):
                list_ = []

                try:
                    list_.append(k['user_id'])
                except Exception:
                    list_.append(None)
                try:
                    list_.append(k['items'][i]['id'])
                except Exception:
                    list_.append(None)
                try:
                    list_.append(k['items'][i]['sex'])
                except Exception:
                    list_.append(None)
                try:
                    list_.append(k['items'][i]['bdate'])
                except Exception:
                    list_.append(None)
                try:
                    list_.append(k['items'][i]['relation'])
                except Exception:
                    list_.append(None)
                try:
                    list_.append(k['items'][i]['city']['title'])
                except Exception:
                    list_.append(None)
                try:
                    list_.append(k['items'][i]['country']['title'])
                except Exception:
                    list_.append(None)
                try:
                    list_.append(k['items'][i]['schools'][0]['year_graduated'])
                except Exception:
                    list_.append(None)
                try:
                    list_.append(k['items'][i]['universities'][0]['chair_name'])
                except Exception:
                    list_.append(None)
                try:
                    list_.append(k['items'][i]['universities'][0]['faculty_name'])
                except Exception:
                    list_.append(None)
                try:
                    list_.append(k['items'][i]['universities'][0]['graduation'])
                except Exception:
                    list_.append(None)
                list_for_df.append(list_)

user_and_frends_info = pd.DataFrame(list_for_df)
user_and_frends_info.columns = ['user_id', 'friend_id', 'sex', 'birthday', 'relation', 'city', 'country',
                                'school_year_graduated', 'universities_chair_name', 
                                'universities_faculty_name', 'universities_graduation']

  0%|          | 0/3531 [00:00<?, ?it/s]
  0%|          | 1/3531 [00:01<1:25:26,  1.45s/it]
  0%|          | 2/3531 [00:03<1:31:35,  1.56s/it]
  0%|          | 3/3531 [00:04<1:29:44,  1.53s/it]
  0%|          | 4/3531 [00:06<1:35:01,  1.62s/it]
  0%|          | 5/3531 [00:07<1:25:18,  1.45s/it]
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/anaconda3/lib/python3.5/site-packages/tqdm/_tqdm.py", line 102, in run
    for instance in self.tqdm_cls._instances:
  File "/anaconda3/lib/python3.5/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration

100%|██████████| 3531/3531 [2:02:05<00:00,  2.07it/s]

In [51]:
my_df = user_and_frends_info.copy()


for i, row in my_df[my_df['birthday'].notnull()].iterrows():
    if len(row['birthday']) <= 5:
        my_df.loc[i, 'birthday'] = None
my_df['birthday'] = pd.to_datetime(my_df['birthday'], format = '%d.%m.%Y')
my_df['birthday'] = datetime(2016,12,11) - my_df['birthday']
my_df['birthday']

TypeError: object of type 'Timestamp' has no len()

In [52]:
user_and_frends_info

,user_id,friend_id,sex,birthday,relation,city,country,school_year_graduated,universities_chair_name,universities_faculty_name,universities_graduation
0,33186,747,1,1989-07-22,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
1,33186,795,2,1989-09-13,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
2,33186,811,2,1988-08-26,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
3,33186,976,1,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
4,33186,4413,2,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
5,33186,5878,1,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
6,33186,6132,1,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
7,33186,6356,2,1988-12-16,0.0,Санкт-Петербург,Россия,2006.0,Международной журналистики\r\n,Факультет журналистики (Высшая школа журналист...,NaN
8,33186,6707,1,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
9,33186,7071,1,1989-01-03,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
10,33186,9148,1,1987-12-01,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
11,33186,9180,2,NaT,0.0,None,Россия,NaN,Механики и процессов управления,Институт прикладной математики и механики,NaN
12,33186,13444,1,NaT,4.0,Санкт-Петербург,Россия,2004.0,Смольный институт свободных искусств и наук,Факультет свободных искусств и наук,NaN
13,33186,17057,2,1987-06-01,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
14,33186,17346,1,NaT,NaN,None,Россия,NaN,None,None,NaN
15,33186,18002,1,1988-12-24,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
16,33186,18366,2,NaT,NaN,None,None,NaN,None,None,NaN
17,33186,18774,1,NaT,0.0,Санкт-Петербург,Россия,NaN,Связи с общественностью,Гуманитарный факультет,2011.0
18,33186,24596,1,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
19,33186,25049,1,NaT,NaN,Москва,Россия,NaN,None,None,NaN
20,33186,25723,2,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
21,33186,26052,1,1986-07-09,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
22,33186,26060,1,1989-07-27,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
23,33186,28092,2,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
24,33186,28171,2,NaT,NaN,None,None,NaN,None,None,NaN
25,33186,28922,1,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
26,33186,29597,1,1989-09-21,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
27,33186,30619,2,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
28,33186,31113,1,1987-05-26,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
29,33186,32184,2,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...
31990,873519,184764322,1,NaT,4.0,Санкт-Петербург,Россия,NaN,None,None,NaN
31991,873519,186913277,2,NaT,0.0,Санкт-Петербург,Россия,1996.0,None,None,NaN
31992,873519,187220432,2,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
31993,873519,210188649,1,NaT,0.0,Санкт-Петербург,Россия,NaN,None,None,NaN
31994,873519,210627664,1,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
31995,873519,221225318,2,NaT,0.0,Санкт-Петербург,Россия,NaN,None,None,NaN
31996,873519,239590180,2,1988-07-01,0.0,Великий Новгород,Россия,NaN,None,Факультет управления (Институт экономики и упр...,2011.0
31997,873519,242961555,2,1987-01-09,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
31998,873519,271799240,1,1986-03-06,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
31999,873519,276327530,2,1901-04-14,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
32000,873519,279270021,2,NaT,0.0,Санкт-Петербург,Россия,NaN,None,None,NaN
32001,873519,284018370,1,NaT,4.0,Санкт-Петербург,Россия,NaN,Здания,Вечерний,1978.0
32002,873519,295989324,2,1966-09-21,0.0,Санкт-Петербург,Россия,NaN,None,None,NaN
32003,873519,297614911,2,NaT,NaN,Сочи,Россия,NaN,None,None,NaN
32004,873519,300108514,2,NaT,0.0,None,None,NaN,None,None,NaN
32005,873519,301098971,2,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
32006,873519,307825845,2,1973-05-25,1.0,Санкт-Петербург,Россия,NaN,None,None,NaN
32007,873519,312987864,2,NaT,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
32008,873519,314262471,2,NaT,3.0,Санкт-Петербург,Россия,NaN,None,None,NaN
32009,873519,314490943,2,1982-02-03,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
32010,873519,317494361,2,1986-02-02,1.0,Москва,Россия,2003.0,None,"Институт радиотехники, электроники и связи",NaN
32011,873519,328723850,1,NaT,6.0,Санкт-Петербург,Россия,NaN,None,None,NaN
32012,873519,339087384,2,NaT,4.0,Санкт-Петербург,Россия,NaN,None,None,NaN
32013,873519,343876031,2,1998-12-27,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
32014,873519,352994836,2,NaT,0.0,Санкт-Петербург,Россия,NaN,None,None,NaN
32015,873519,368100150,1,NaT,0.0,Санкт-Петербург,Россия,NaN,None,None,NaN
32016,873519,374737900,1,1978-09-30,0.0,None,None,NaN,None,None,NaN
32017,873519,378243570,1,1984-01-05,NaN,Санкт-Петербург,Россия,NaN,None,None,NaN
32018,873519,386815543,2,1977-09-29,4.0,Санкт-Петербург,Россия,NaN,None,None,NaN
32019,873519,387036032,2,NaT,NaN,None,None,NaN,None,None,NaN

In [ ]:
user_and_frends_info.to_csv('data/vk/user_and_frends_info')

In [11]:
# Максим:
user_and_frends_info.user_id.value_counts()

673666    2886
752811    2630
569663    2397
235404    1881
724244    1730
571574    1452
832925    1147
531359    1129
699388     889
281782     857
256110     746
236711     713
225365     712
33186      668
269126     653
801360     650
772153     642
518934     642
202190     570
37259      544
742366     509
827095     502
862735     478
63923      476
730935     437
506753     427
732809     413
36415      394
423598     365
417914     353
280926     331
676897     322
873519     294
657236     289
758217     276
604396     263
160308     263
369818     262
609579     231
594540     196
648320     184
467709     177
71914      169
652691     156
304252     150
455548     142
793260     133
812486     110
478070      88
382491      47
831156      45
Name: user_id, dtype: int64

In [14]:
user_and_frends_info.drop_duplicates().shape

(32020, 11)